/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/system/info": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read service status. */
    get: operations["getSystemInfo"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/bootstrap-admin": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create the first admin while the installation has no users. */
    post: operations["bootstrapAdmin"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/register": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Register by invitation code. */
    post: operations["registerByInvitation"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Login by email and password. */
    post: operations["login"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/refresh": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Rotate refresh token from httpOnly cookie. */
    post: operations["refresh"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Revoke current refresh token. */
    post: operations["logout"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/change-password": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Change current user password. */
    post: operations["changePassword"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read current user profile. */
    get: operations["getCurrentUser"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/users": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List users. */
    get: operations["listUsers"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/invitations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create an admin or lecturer invitation. */
    post: operations["createAdminInvitation"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/identity/link-codes": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create a short code for linking a channel identity. */
    post: operations["createIdentityLinkCode"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/identity/link": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Link channel identity by code. */
    post: operations["linkIdentity"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/courses": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List courses visible to current user. */
    get: operations["listCourses"];
    put?: never;
    /** Create a course. */
    post: operations["createCourse"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/courses/{courseId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read one course. */
    get: operations["getCourse"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/courses/{courseId}/invitations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create an invitation for a course or group. */
    post: operations["createCourseInvitation"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/courses/{courseId}/members": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List course members. */
    get: operations["listCourseMembers"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/courses/{courseId}/groups": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List study groups. */
    get: operations["listStudyGroups"];
    put?: never;
    /** Create a study group. */
    post: operations["createStudyGroup"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/courses/{courseId}/bans": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List course bans. */
    get: operations["listCourseBans"];
    put?: never;
    /** Ban a person from a course. */
    post: operations["banCourseMember"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/courses/{courseId}/decks": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List slide decks for a course. */
    get: operations["listSlideDecks"];
    put?: never;
    /** Upload a presentation file and start a background import job. */
    post: operations["importSlideDeck"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/courses/{courseId}/import-jobs/{jobId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read slide deck import job status. */
    get: operations["getImportJob"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/courses/{courseId}/decks/{deckId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read one slide deck with slides. */
    get: operations["getSlideDeck"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/courses/{courseId}/decks/{deckId}/slides/{slideIndex}/image": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read rendered slide image. */
    get: operations["getSlideImage"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/courses/{courseId}/decks/{deckId}/slides/{slideIndex}/notes": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Save lecturer notes for one slide. */
    put: operations["saveSlideNote"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/courses/{courseId}/lectures": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List lecture materials for a course. */
    get: operations["listLectures"];
    put?: never;
    /** Create lecture material. */
    post: operations["createLecture"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/courses/{courseId}/lectures/{lectureId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read lecture material. */
    get: operations["getLecture"];
    /** Update lecture material. */
    put: operations["updateLecture"];
    post?: never;
    /** Archive lecture material. */
    delete: operations["deleteLecture"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/courses/{courseId}/lectures/{lectureId}/attachments": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Upload an arbitrary file attached to a lecture. */
    post: operations["uploadLectureAttachment"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    SystemInfo: {
      /** @example lecturer-assistant-v2 */
      name: string;
      /** @example 0.0.1-SNAPSHOT */
      version: string;
      /** @enum {string} */
      status: "BOOTSTRAPPED";
    };
    RegisterRequest: {
      displayName: string;
      /** Format: email */
      email: string;
      password: string;
    };
    LoginRequest: {
      /** Format: email */
      email: string;
      password: string;
    };
    ChangePasswordRequest: {
      currentPassword: string;
      newPassword: string;
    };
    AuthResponse: {
      accessToken: string;
      user: components["schemas"]["UserProfile"];
    };
    UserProfile: {
      /** Format: uuid */
      id: string;
      displayName: string;
      /** Format: email */
      email: string;
      /** @enum {string} */
      role: "ADMIN" | "LECTURER" | "ASSISTANT" | "STUDENT";
      /** @enum {string} */
      status: "ACTIVE" | "DISABLED" | "EPHEMERAL";
    };
    CreateInvitationRequest: {
      /** @enum {string} */
      role: "ADMIN" | "LECTURER" | "ASSISTANT";
      /** @default 168 */
      ttlHours: number;
    };
    CreateCourseInvitationRequest: {
      /** @enum {string} */
      role: "LECTURER" | "ASSISTANT" | "STUDENT";
      /** Format: uuid */
      groupId?: string;
      /** @default 168 */
      ttlHours: number;
    };
    Invitation: {
      /** Format: uuid */
      id: string;
      code: string;
      /** @enum {string} */
      role: "ADMIN" | "LECTURER" | "ASSISTANT" | "STUDENT";
      /** Format: uuid */
      courseId?: string;
      /** Format: uuid */
      groupId?: string;
      /** Format: date-time */
      expiresAt: string;
    };
    IdentityLinkCode: {
      code: string;
      /** Format: date-time */
      expiresAt: string;
    };
    LinkIdentityRequest: {
      code: string;
      /** @enum {string} */
      channelType: "telegram" | "vk" | "web";
      externalId: string;
      displayHint?: string;
    };
    ChannelIdentity: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      personId: string;
      channelType: string;
      externalId: string;
      displayHint?: string;
      /** Format: date-time */
      linkedAt: string;
    };
    CreateCourseRequest: {
      title: string;
    };
    Course: {
      /** Format: uuid */
      id: string;
      title: string;
      /** Format: uuid */
      ownerPersonId: string;
      archived: boolean;
    };
    CourseDetails: components["schemas"]["Course"] & {
      myRole?: components["schemas"]["CourseRole"];
      canManage: boolean;
      members: components["schemas"]["CourseMember"][];
      groups: components["schemas"]["StudyGroup"][];
    };
    CourseMember: {
      /** Format: uuid */
      courseId: string;
      /** Format: uuid */
      personId: string;
      displayName: string;
      role: components["schemas"]["CourseRole"];
    };
    /** @enum {string} */
    CourseRole: "LECTURER" | "ASSISTANT" | "STUDENT";
    CreateStudyGroupRequest: {
      name: string;
    };
    StudyGroup: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      courseId: string;
      name: string;
    };
    BanCourseMemberRequest: {
      /** Format: uuid */
      personId: string;
      reason?: string;
    };
    CourseBan: {
      /** Format: uuid */
      courseId: string;
      /** Format: uuid */
      personId: string;
      reason?: string;
      /** Format: date-time */
      bannedAt: string;
    };
    ImportJob: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      courseId: string;
      /** Format: uuid */
      deckId?: string;
      /** @enum {string} */
      status: "PENDING" | "RUNNING" | "COMPLETED" | "FAILED";
      progressPercent: number;
      sourceFilename: string;
      errorMessage?: string;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    SlideDeck: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      courseId: string;
      title: string;
      version: number;
      sourceFilename?: string;
      slideCount: number;
      /** Format: date-time */
      createdAt: string;
    };
    SlideDeckDetails: components["schemas"]["SlideDeck"] & {
      slides: components["schemas"]["Slide"][];
    };
    Slide: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      deckId: string;
      idx: number;
      imageUrl: string;
      textExtract?: string;
      note?: components["schemas"]["SlideNote"];
    };
    SlideNote: {
      /** Format: uuid */
      slideId: string;
      content: string;
      /** Format: date-time */
      updatedAt: string;
    };
    SaveSlideNoteRequest: {
      content: string;
    };
    CreateLectureRequest: {
      title: string;
      /** Format: uuid */
      deckId: string;
      defaultSettings?: {
        [key: string]: unknown;
      };
    };
    Lecture: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      courseId: string;
      title: string;
      /** Format: uuid */
      deckId: string;
      archived: boolean;
      /** Format: date-time */
      createdAt: string;
    };
    LectureDetails: components["schemas"]["Lecture"] & {
      deck?: components["schemas"]["SlideDeck"];
      attachments: components["schemas"]["Attachment"][];
    };
    Attachment: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      lectureId: string;
      filename: string;
      contentType: string;
      /** Format: int64 */
      sizeBytes: number;
      /** Format: date-time */
      createdAt: string;
    };
  };
  responses: never;
  parameters: {
    CourseId: string;
    DeckId: string;
    JobId: string;
    LectureId: string;
    SlideIndex: number;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getSystemInfo: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Service status. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SystemInfo"];
        };
      };
    };
  };
  bootstrapAdmin: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RegisterRequest"];
      };
    };
    responses: {
      /** @description Authenticated admin. */
      200: {
        headers: {
          /** @description httpOnly refresh token cookie scoped to /api/v1/auth. */
          "Set-Cookie"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthResponse"];
        };
      };
      /** @description Installation already has users. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  registerByInvitation: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RegisterRequest"] & {
          invitationCode: string;
        };
      };
    };
    responses: {
      /** @description Registered person and access token. */
      200: {
        headers: {
          /** @description httpOnly refresh token cookie scoped to /api/v1/auth. */
          "Set-Cookie"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthResponse"];
        };
      };
      /** @description Invalid invitation. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequest"];
      };
    };
    responses: {
      /** @description Authenticated person and access token. */
      200: {
        headers: {
          /** @description httpOnly refresh token cookie scoped to /api/v1/auth. */
          "Set-Cookie"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthResponse"];
        };
      };
      /** @description Invalid credentials. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  refresh: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Refreshed tokens. */
      200: {
        headers: {
          /** @description Rotated httpOnly refresh token cookie scoped to /api/v1/auth. */
          "Set-Cookie"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthResponse"];
        };
      };
      /** @description Invalid refresh token. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Logged out. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  changePassword: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ChangePasswordRequest"];
      };
    };
    responses: {
      /** @description Password changed. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getCurrentUser: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Current user. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserProfile"];
        };
      };
    };
  };
  listUsers: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Users. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserProfile"][];
        };
      };
    };
  };
  createAdminInvitation: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateInvitationRequest"];
      };
    };
    responses: {
      /** @description Created invitation. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Invitation"];
        };
      };
    };
  };
  createIdentityLinkCode: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Link code. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IdentityLinkCode"];
        };
      };
    };
  };
  linkIdentity: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LinkIdentityRequest"];
      };
    };
    responses: {
      /** @description Linked channel identity. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ChannelIdentity"];
        };
      };
    };
  };
  listCourses: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Courses. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Course"][];
        };
      };
    };
  };
  createCourse: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateCourseRequest"];
      };
    };
    responses: {
      /** @description Created course. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Course"];
        };
      };
    };
  };
  getCourse: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        courseId: components["parameters"]["CourseId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Course. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CourseDetails"];
        };
      };
      /** @description Course is not visible to current user. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  createCourseInvitation: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        courseId: components["parameters"]["CourseId"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateCourseInvitationRequest"];
      };
    };
    responses: {
      /** @description Created invitation. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Invitation"];
        };
      };
    };
  };
  listCourseMembers: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        courseId: components["parameters"]["CourseId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Members. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CourseMember"][];
        };
      };
    };
  };
  listStudyGroups: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        courseId: components["parameters"]["CourseId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Study groups. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StudyGroup"][];
        };
      };
    };
  };
  createStudyGroup: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        courseId: components["parameters"]["CourseId"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateStudyGroupRequest"];
      };
    };
    responses: {
      /** @description Created group. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StudyGroup"];
        };
      };
    };
  };
  listCourseBans: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        courseId: components["parameters"]["CourseId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Course bans. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CourseBan"][];
        };
      };
    };
  };
  banCourseMember: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        courseId: components["parameters"]["CourseId"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["BanCourseMemberRequest"];
      };
    };
    responses: {
      /** @description Created ban. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CourseBan"];
        };
      };
    };
  };
  listSlideDecks: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        courseId: components["parameters"]["CourseId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Slide decks. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SlideDeck"][];
        };
      };
    };
  };
  importSlideDeck: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        courseId: components["parameters"]["CourseId"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "multipart/form-data": {
          /** Format: binary */
          file: string;
          title: string;
        };
      };
    };
    responses: {
      /** @description Import job accepted. */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ImportJob"];
        };
      };
    };
  };
  getImportJob: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        courseId: components["parameters"]["CourseId"];
        jobId: components["parameters"]["JobId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Import job. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ImportJob"];
        };
      };
    };
  };
  getSlideDeck: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        courseId: components["parameters"]["CourseId"];
        deckId: components["parameters"]["DeckId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Slide deck details. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SlideDeckDetails"];
        };
      };
    };
  };
  getSlideImage: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        courseId: components["parameters"]["CourseId"];
        deckId: components["parameters"]["DeckId"];
        slideIndex: components["parameters"]["SlideIndex"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Slide image. */
      200: {
        headers: {
          /** @description Long-lived immutable cache header. */
          "Cache-Control"?: string;
          [name: string]: unknown;
        };
        content: {
          "image/png": string;
        };
      };
    };
  };
  saveSlideNote: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        courseId: components["parameters"]["CourseId"];
        deckId: components["parameters"]["DeckId"];
        slideIndex: components["parameters"]["SlideIndex"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SaveSlideNoteRequest"];
      };
    };
    responses: {
      /** @description Saved note. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SlideNote"];
        };
      };
    };
  };
  listLectures: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        courseId: components["parameters"]["CourseId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Lectures. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Lecture"][];
        };
      };
    };
  };
  createLecture: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        courseId: components["parameters"]["CourseId"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateLectureRequest"];
      };
    };
    responses: {
      /** @description Created lecture. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Lecture"];
        };
      };
    };
  };
  getLecture: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        courseId: components["parameters"]["CourseId"];
        lectureId: components["parameters"]["LectureId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Lecture material. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LectureDetails"];
        };
      };
    };
  };
  updateLecture: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        courseId: components["parameters"]["CourseId"];
        lectureId: components["parameters"]["LectureId"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateLectureRequest"];
      };
    };
    responses: {
      /** @description Updated lecture. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Lecture"];
        };
      };
    };
  };
  deleteLecture: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        courseId: components["parameters"]["CourseId"];
        lectureId: components["parameters"]["LectureId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Lecture archived. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  uploadLectureAttachment: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        courseId: components["parameters"]["CourseId"];
        lectureId: components["parameters"]["LectureId"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "multipart/form-data": {
          /** Format: binary */
          file: string;
        };
      };
    };
    responses: {
      /** @description Uploaded attachment. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Attachment"];
        };
      };
    };
  };
}
